---

name: build

on:
  push:
    branches: 
      - main
  # schedule:
  #   - cron: '0 6 1 * *'

env:
  PLATFORM: "linux/amd64,linux/arm64/v8"
  DEBIAN_VERSION: "bullseye"
  GO_VERSION: "1.18"
  KUBECTL_VERSION: "v1.24.1"
  PYTHON_VERSION: "3.10"
  ANSIBLE_VERSION: "5.9.0"

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build toolbox
        run: |
          docker buildx build --target toolbox \
            --build-arg DEBIAN_VERSION=$DEBIAN_VERSION \
            --build-arg GO_VERSION=$GO_VERSION \
            --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION \
            --tag ${{ secrets.DOCKER_USERNAME }}/ci-toolbox:$DEBIAN_VERSION \
            --platform $PLATFORM --output type=registry .

      - name: Build kubectl
        run: |
          docker buildx build --target kubectl \
            --build-arg DEBIAN_VERSION=$DEBIAN_VERSION \
            --build-arg GO_VERSION=$GO_VERSION \
            --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION \
            --tag ${{ secrets.DOCKER_USERNAME }}/ci-kubectl:$KUBECTL_VERSION \
            --platform $PLATFORM --output type=registry .

      - name: Build ansible
        run: |
          docker buildx build --target ansible \
            --build-arg DEBIAN_VERSION=$DEBIAN_VERSION \
            --build-arg GO_VERSION=$GO_VERSION \
            --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION \
            --tag ${{ secrets.DOCKER_USERNAME }}/ci-ansible:$ANSIBLE_VERSION \
            --platform $PLATFORM --output type=registry .

      - name: Unlogin to docker hub
        run: docker logout
