---

name: build

on:
  push:
    branches: 
      - master

env:
  PLATFORM: "linux/amd64,linux/arm64/v8,linux/arm/v7"
  DEBIAN_VERSION: "bullseye"
  GO_VERSION: "1.18"
  KUBECTL_VERSION: "v1.24.1"
  PYTHON_VERSION: "3.10"
  ANSIBLE_VERSION: "5.8.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build toolbox
        run: >-
          docker buildx build --push --target toolbox
            --build-arg "DEBIAN_VERSION=$DEBIAN_VERSION"
            --build-arg "GO_VERSION=$GO_VERSION"
            --build-arg "KUBECTL_VERSION=$KUBECTL_VERSION"
            --build-arg "PYTHON_VERSION=$PYTHON_VERSION"
            --build-arg "ANSIBLE_VERSION=$ANSIBLE_VERSION"
            --tag "${{ secrets.DOCKER_USERNAME }}/ci-toolbox:$DEBIAN_VERSION"
            --platform "$PLATFORM" .

      - name: build kubectl
        run: >-
          docker buildx build --push --target kubectl
            --build-arg "DEBIAN_VERSION=$DEBIAN_VERSION"
            --build-arg "GO_VERSION=$GO_VERSION"
            --build-arg "KUBECTL_VERSION=$KUBECTL_VERSION"
            --build-arg "PYTHON_VERSION=$PYTHON_VERSION"
            --build-arg "ANSIBLE_VERSION=$ANSIBLE_VERSION"
            --tag "${{ secrets.DOCKER_USERNAME }}/ci-kubectl:$KUBECTL_VERSION"
            --platform "$PLATFORM" .

      - name: build ansible
        run: >-
          docker buildx build --push --target ansible
            --build-arg "DEBIAN_VERSION=$DEBIAN_VERSION"
            --build-arg "GO_VERSION=$GO_VERSION"
            --build-arg "KUBECTL_VERSION=$KUBECTL_VERSION"
            --build-arg "PYTHON_VERSION=$PYTHON_VERSION"
            --build-arg "ANSIBLE_VERSION=$ANSIBLE_VERSION"
            --tag "${{ secrets.DOCKER_USERNAME }}/ci-ansible:$ANSIBLE_VERSION"
            --platform "$PLATFORM" .

      - name: unlogin to docker hub
        run: docker logout
